rootProject.name = "quicksort-polyglot"
include("quicksort-polyglot-api")
include("quicksort-polyglot-scripted-factory")
include("quicksort-polyglot-java")
include("quicksort-polyglot-test")
include("quicksort-polyglot-kotlin")
include("quicksort-polyglot-scala")
include("quicksort-polyglot-js")
include("quicksort-polyglot-groovy")
include("quicksort-polyglot-clojure")
include("quicksort-polyglot-jruby")
